# Generated by Django 4.2.1 on 2023-05-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgetype',
            name='make_comments',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='badgetype',
            name='put_reactions',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
