# Generated by Django 4.2.1 on 2023-05-27 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_override_permissions',
            field=models.ManyToManyField(blank=True, related_name='post_override_permissions', to='base.badgetype'),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_override_permissions',
            field=models.ManyToManyField(blank=True, related_name='topic_override_permissions', to='base.badgetype'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
