# Generated by Django 4.2.1 on 2023-05-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post_post_override_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_override_permissions',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_override_permissions',
        ),
        migrations.AddField(
            model_name='badgetype',
            name='make_posts',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='banned_users_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
