# Generated by Django 4.2.1 on 2023-05-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_badgetype_make_comments_badgetype_put_reactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badgetype',
            old_name='put_reactions',
            new_name='make_reactions_comments',
        ),
        migrations.AddField(
            model_name='badgetype',
            name='make_profile_posts',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='badgetype',
            name='make_reactions_post',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(blank=True, to='base.badgetype'),
        ),
    ]
