# Generated by Django 4.2.1 on 2023-05-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_post_post_override_permissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badgetype',
            old_name='make_posts',
            new_name='make_posts_perm',
        ),
    ]
