# Generated by Django 4.2.1 on 2023-05-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_put_reactions_badgetype_make_reactions_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgetype',
            name='delete_profile_posts',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
