# Generated by Django 4.2.1 on 2023-05-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_badgetype_delete_profile_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgetype',
            name='pin_posts_perm',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='badgetype',
            name='unpin_posts_perm',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
