# Generated by Django 4.2.1 on 2023-05-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_make_posts_badgetype_make_posts_perm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='task_id',
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge_duration',
            field=models.DurationField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='date_applied',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
