# Generated by Django 4.1.4 on 2023-01-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_comment_rename_host_post_user_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('TU', 'ThumbsUp'), ('SD', 'Sad'), ('TD', 'ThumbsDown'), ('AG', 'Angry'), ('LA', 'Laughing')], max_length=2, null=True),
        ),
    ]
