# Generated by Django 4.1.4 on 2023-01-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_user_score_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='front_sticky',
            field=models.CharField(choices=[('RU', 'Rules'), ('CO', 'Community'), ('DR', 'DarkRP'), ('MR', 'MilitaryRP'), ('PR', 'PrisonRP')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='front_sticky',
            field=models.CharField(choices=[('RU', 'Rules'), ('CO', 'Community'), ('DR', 'DarkRP'), ('MR', 'MilitaryRP'), ('PR', 'PrisonRP')], max_length=2, null=True),
        ),
    ]
