# Generated by Django 4.1.4 on 2023-01-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_post_front_sticky_topic_front_sticky'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='front_sticky',
            field=models.CharField(blank=True, choices=[('RU', 'Rules'), ('CO', 'Community'), ('DR', 'DarkRP'), ('MR', 'MilitaryRP'), ('PR', 'PrisonRP')], max_length=2, null=True),
        ),
    ]
