# Generated by Django 4.1.4 on 2023-01-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_topic_front_sticky'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='front_sticky',
            field=models.CharField(choices=[('RU', 'Rules'), ('CO', 'Community'), ('DR', 'DarkRP'), ('MR', 'MilitaryRP'), ('PR', 'PrisonRP')], max_length=2, null=True),
        ),
    ]
