# Generated by Django 4.1.4 on 2023-01-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_user_registration_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_id',
        ),
        migrations.AddField(
            model_name='user',
            name='register',
            field=models.CharField(default='', max_length=255),
        ),
    ]
