# Generated by Django 4.1.4 on 2023-02-15 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_comment_options_post_is_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='reaction_images/')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.reactiontypes'),
        ),
    ]
