# Generated by Django 4.1.4 on 2023-02-17 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_post_is_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontStickyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='front_sticky',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.frontstickytype'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='front_sticky',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.frontstickytype'),
        ),
    ]
