# Generated by Django 4.1.4 on 2023-02-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_frontstickytype_alter_post_front_sticky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
