# Generated by Django 4.1.4 on 2023-02-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_topic_is_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
