# Generated by Django 4.1.4 on 2023-02-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_profilepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepost',
            name='content',
            field=models.CharField(default='hello', max_length=200),
            preserve_default=False,
        ),
    ]
