# Generated by Django 4.1.4 on 2023-02-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background',
            field=models.ImageField(default='default.png', upload_to='uploads/'),
        ),
    ]
