# Generated by Django 4.1.4 on 2023-02-25 16:26

import base.formatChecker
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_user_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=base.formatChecker.ContentTypeRestrictedFileField(default='default.png', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='background',
            field=base.formatChecker.ContentTypeRestrictedFileField(default='default.png', upload_to='uploads/'),
        ),
    ]
