# Generated by Django 4.1.4 on 2023-03-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_badge_badgetype_alter_comment_options_delete_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgetype',
            name='html',
            field=models.TextField(max_length=200, unique=True),
        ),
    ]
