# Generated by Django 4.1.4 on 2023-03-21 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_badgetype_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='badge_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.badgetype'),
            preserve_default=False,
        ),
    ]
