# Generated by Django 4.1.4 on 2023-03-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_user_badges_delete_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='register',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
