# Generated by Django 4.1.4 on 2023-03-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_alter_user_password_alter_user_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
