# Generated by Django 4.1.4 on 2023-03-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_user_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgetype',
            name='edit_comments_perm',
            field=models.BooleanField(default=False),
        ),
    ]
