# Generated by Django 4.1.4 on 2023-03-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_badgetype_inheritance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgetype',
            name='edit_comments_perm',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
