# Generated by Django 4.1.4 on 2023-03-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_alter_badgetype_inheritance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
