# Generated by Django 4.1.4 on 2023-03-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='view_permisions',
            field=models.ManyToManyField(to='base.badgetype'),
        ),
    ]
