# Generated by Django 4.1.4 on 2023-03-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_topic_view_permisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgetype',
            name='edit_posts_perm',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
