# Generated by Django 4.1.4 on 2023-03-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_alter_post_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='topic',
            new_name='parrent_topic',
        ),
    ]
