# Generated by Django 4.1.4 on 2023-03-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_rename_topic_post_parrent_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgetype',
            name='html',
            field=models.TextField(max_length=9999, unique=True),
        ),
    ]
