# Generated by Django 4.1.4 on 2023-03-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_comment_deleted_by_comment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgetype',
            name='delete_comments_perm',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='badgetype',
            name='see_deleted_comments_perm',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
