# Generated by Django 4.1.4 on 2023-03-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_alter_comment_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgetype',
            name='make_comments_perm',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
