# Generated by Django 4.1.4 on 2023-03-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_badgetype_make_comments_perm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badgetype',
            old_name='make_comments_perm',
            new_name='make_comments_on_locked_perm',
        ),
    ]
