# Generated by Django 4.1.4 on 2023-03-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_rename_make_comments_perm_badgetype_make_comments_on_locked_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgetype',
            name='lock_post_perm',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
