# Generated by Django 4.1.4 on 2023-03-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_badgetype_lock_post_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgetype',
            name='unlock_post_perm',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
