# Generated by Django 4.1.4 on 2023-03-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_comment_edited_by_comment_has_new_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgetype',
            name='see_comment_history',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
