# Generated by Django 4.1.4 on 2023-04-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_alter_notificationsubscribe_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationSubscribe',
        ),
    ]
