# Generated by Django 4.1.4 on 2023-04-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('base', '0069_notificationsubscribe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
