# Generated by Django 4.1.4 on 2023-04-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('base', '0070_alter_notification_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_type',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(default=None, max_length=99999),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('user', 'content_type', 'object_id', 'action_type')},
        ),
    ]
