# Generated by Django 4.1.4 on 2023-04-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_alter_notification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['created']},
        ),
    ]
