# Generated by Django 4.1.4 on 2023-04-07 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('base', '0078_alter_topic_view_permisions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notification',
            name='subscribed_object_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='subscribed_object_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_object_type', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='view_permisions',
            field=models.ManyToManyField(blank=True, null=True, to='base.badgetype'),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('user', 'subscribed_object_type', 'subscribed_object_id', 'action_type')},
        ),
    ]
