# Generated by Django 4.1.4 on 2023-04-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_alter_notification_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='view_permisions',
            field=models.ManyToManyField(blank=True, to='base.badgetype'),
        ),
    ]
