# Generated by Django 4.1.4 on 2023-04-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_alter_topic_view_permisions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('seen', False)), fields=('user', 'subscribed_object_type', 'subscribed_object_id', 'action_type'), name='unique_field_a_field_b_validated'),
        ),
    ]
