# Generated by Django 4.1.4 on 2023-04-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_post_deleted_by_post_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgetype',
            name='see_deleted_post_perm',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
