# Generated by Django 4.2 on 2023-04-24 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_alter_comment_created_alter_post_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 15, 55, 15, 428778, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 15, 55, 15, 427663, tzinfo=datetime.timezone.utc)),
        ),
    ]
