# Generated by Django 4.2 on 2023-04-25 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0086_alter_comment_created_alter_post_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='has_new_version',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='previous',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='edited_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_by_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
