# Generated by Django 4.2 on 2023-04-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_post_edited_by_post_has_new_version_post_previous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgetype',
            name='see_post_history',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
