# Generated by Django 4.2 on 2023-05-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_badgetype_see_post_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgetype',
            name='move_threads_perm',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
